set nocompatible
set termguicolors

" set colorscheme
colorscheme base16-one-light
let base16colorspace=256

" enable syntax highlighting
filetype plugin on
syntax enable 

" enable indentation
filetype indent on

" enable mouse usage
set mouse=a

" show line numbers
set number

" highlight search results
set incsearch

""""""""""""""""
" FINDING FILES
""""""""""""""""
" Search down into subfolders
" Provides tab-completion for all file-related tasks
set path+=**

" Display all matching files when we tab complete
set wildmenu


"""""""""""""""
" FILE BROWSING
"""""""""""""""
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 2
let g:netrw_altv = 1
let g:netrw_winsize = 15
augroup ProjectDrawer
  autocmd!
  autocmd VimEnter * if argc() == 0 | Explore! | endif
augroup END
